services:
  eureka-server:
    build: ./EurekaServer
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  stock-service:
    build: ./StockService
    container_name: stock-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server

  currency-converter:
    build: ./CurrencyConverter
    container_name: currency-converter
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server

  portfolio-service:
    build: ./PortfolioService
    container_name: portfolio-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - stock-service
      - currency-converter
